### PR TITLE
Fix 'update' command reporting success on network failure

### LINKED ISSUE #22: `update` does nothing and says it succeeded if you're offline
```
$ time cargo supply-chain update --cache-max-age '1s'
Successfully updated to the newest daily data dump.

real	0m0.048s
user	0m0.036s
sys	0m0.012s
```

### PR DESCRIPTION
**Pull request by Shnatsel**
Fixes #22

### CODE REVIEW

File: src/crates_cache.rs [hunk 1]
```diff
@@ -137,6 +137,11 @@ impl CratesCache {
             request.call()
         };
 
+        if response.error() {
+            let err = response.synthetic_error().as_ref().unwrap();
+            return Err(io::Error::new(io::ErrorKind::Other, format!("{}", err)));
+        }
```
Comment (HeroicKatora) [inline src/crates_cache.rs:143]: Nit: The response could be an error without that error being synthetic. The real server could return an error.

Comment (Shnatsel) [reply src/crates_cache.rs]: Good catch! Fixed, thanks!
